### PR TITLE
NGI upload option

### PR DESCRIPTION
**Pull request by Smeds**
Added the option of uploading data to NGI-pipeline host, will upload the files needed by NGI. Is triggered by flag -uploadForNGIanalysis.

### CODE REVIEW

**Comment by johandahlberg** [comment]
I'd suggest making this a bit more general in it's naming, both in the actual parameters, but also in the code. Saying something like `--altHostUpload` (just a suggestion), etc.

**Comment by MatildaAslin** [comment]
Yeah, sounds like a good idea.

**Comment by Smeds** [comment]
It's really not an alternative upload procedure, i.e it differs from the regular upload procedure and will only upload the files needed to process the data using NGI-pipeline. Which is a subset of the file and folders that are uploaded during a standard analysis,  it also changes the Unaligned folder into Demultiplexing. Data will still be uploaded to milou and processed as usually.

We could change the naming, but it would make it harder to show whats actually happening.

**Comment by MatildaAslin** [comment]
Good job! :+1:

**Pull request merged**
