### PR TITLE
bcl2fastq 2.17 updates

### PR DESCRIPTION
**Pull request by Smeds**
Updates for start using bcl2fastq 2.17 with miseq, hiseq and hiseqx.
Also, machine type will be retrieved from sisyphus.yml.

### CODE REVIEW

**Comment by MatildaAslin** [comment]
40 files changed :sweat_smile: Looks good!

**Comment by johandahlberg** [comment]
Remember that this contains changes to the way to config files look these also have to be brought into system-management and deployed through there.

**Comment by MatildaAslin** [comment]
Isn't the default sisyphus.yml copied from sisyphus-latest?

**Comment by johandahlberg** [comment]
You are absolutely right. :+1:

**Pull request merged**
