### PR TITLE
Force gzip and no sync to SweStore on Irma

### PR DESCRIPTION
**Pull request by MatildaAslin**
Commit history is a little bit messed up due to not pulling/fetching updated branches as one should do. I fixed the conflicts and it should be fine to merge.

### CODE REVIEW

**Comment by johandahlberg** [comment]
We can have a look at fixing the commit history. But first, there appears to be an issue in the syntax: `syntax error at ./aeacus-reports.pl line 14, near "use Sys::Hostname`

**Comment by johandahlberg** [comment]
Do I understand things correctly when it comes to the zip-ing stuff that it falls back from pigz to gzip when it's not available? I know that is not in the scope of this PR, I'm just thinking that since that will have some pretty large performance implications we might rather want to fail if we really need pigz?

**Comment by johandahlberg** [comment]
Other than those minor comments it looks really good! :trophy:

**Comment by MatildaAslin** [comment]
Ah ofc, a semicolon is missing. 

Yeah, that's how it works. Pigz is actually not installed on the biotanks (I don't know if it ever has been), so that fallback is used everytime when using the -miseq parameter (i.e when a MiseqAnalysis folder is zipped). My guess is that the "real" test is whether the command is executed on one of the biotanks or on an Uppmax cluster.

**Comment by johandahlberg** [comment]
I see. What is the reason that we need to force the zipping?

**Comment by johandahlberg** [comment]
I'm asking all these questions since I'm not that well acquainted with the Sisyphus code.

**Comment by MatildaAslin** [comment]
It solves #131 . But in hindsight I think only the change in readConfig is required to do that. 

Since the changes are so small, I'm going to close this PR and make a new (and clean) branch.

**Pull request closed without merging**
